name: Test CI

on:
  repository_dispatch:
    types: [test]

jobs:
  test-crawler-macOS:

    runs-on: macos-latest
    if: github.event.client_payload.os == 'macos-latest'

    steps:
    - name: Yoyoyo
      run: echo hello macOS

  test-crawler-ubuntu:

    runs-on: ubuntu-latest
    if: github.event.client_payload.os == 'ubuntu-latest'

    steps:
    - name: Yoyoyo
      run: echo hello ubuntu
