name: Test CI

on:
  repository_dispatch:
    types: [test]

jobs:
  test-crawler:

    runs-on: macos-latest
    if: github.event.client_payload.os == 'macos-latest'

    steps:
    - name: Yoyoyo
      run: echo hello
