name: Test CI

on:
  repository_dispatch:
    types: [test]

jobs:
  test-crawler-macOS:
    if: github.event.client_payload.os == 'macos-latest'
    runs-on: macos-latest

    steps:
    - name: Yoyoyo
      run: echo hello macOS

  test-crawler-ubuntu:
    if: github.event.client_payload.os == 'ubuntu-latest'
    runs-on: ubuntu-latest
    
    steps:
    - name: Yoyoyo
      run: echo hello ubuntu
